{{- if .Values.sealedSecret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "vllm.fullname" . }}-lb-ip
  namespace: {{ include "vllm.namespace" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  encryptedData:
    loadBalancerIP: {{ .Values.sealedSecret.encryptedData.loadBalancerIP }}
  template:
    metadata:
      name: {{ include "vllm.fullname" . }}-lb-ip
      namespace: {{ include "vllm.namespace" . }}
      labels:
        {{- include "vllm.labels" . | nindent 8 }}
{{- end }}
