{{- if .Values.sealedSecret.create -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "server.llama.cpp.fullname" . }}-lb-ip
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "server.llama.cpp.labels" . | nindent 4 }}
spec:
  encryptedData:
    loadBalancerIP: {{ .Values.sealedSecret.encryptedData.loadBalancerIP }}
  template:
    metadata:
      name: {{ include "server.llama.cpp.fullname" . }}-lb-ip
      namespace: {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
    type: Opaque
{{- end }}
