{{- if .Values.sealedSecret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "open-webui.name" . }}-secrets
  namespace: {{ include "open-webui.namespace" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  encryptedData:
    LOAD_BALANCER_IP: {{ .Values.sealedSecret.encryptedData.LOAD_BALANCER_IP }}
    SEARCH_API_KEY: {{ .Values.sealedSecret.encryptedData.SEARCH_API_KEY }}
  template:
    metadata:
      name: {{ include "open-webui.name" . }}-secrets
      namespace: {{ include "open-webui.namespace" . }}
      labels:
        {{- include "open-webui.labels" . | nindent 8 }}
{{- end }}
