{{- if .Values.sealedSecret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "open-webui.name" . }}-lb-ip
  namespace: {{ include "open-webui.namespace" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  encryptedData:
    LOAD_BALANCER_IP: {{ .Values.sealedSecret.encryptedData.LOAD_BALANCER_IP }}
  template:
    metadata:
      name: {{ include "open-webui.name" . }}-lb-ip
      namespace: {{ include "open-webui.namespace" . }}
      labels:
        {{- include "open-webui.labels" . | nindent 8 }}
{{- end }}
